services:
  clong:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:clong@db?sslmode=disable
  db:
    image: docker.io/library/postgres
    volumes:
      - db-data:/data/postgres
    environment:
      POSTGRES_PASSWORD: clong
      PG_DATA: /data/postgres

volumes:
  db-data:
