services:
  clong:
    build: .
    command: ["-db-string", "root:clong@db/clong"]
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: docker.io/mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: clong

volumes:
  db-data:
