apiVersion: apps/v1
kind: Deployment
metadata:
  name: clong-db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clong-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clong-db
    spec:
      containers:
        - name: db
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MARIADB_DATABASE
              value: clong
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: clong-credentials
                  key: dbUsername
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: clong-credentials
                  key: dbPassword
