on: [push, pull_request]
name: Lint and Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@master
        with:
          go-version: "1"
      - name: Checkout code
        uses: actions/checkout@master
      - name: Lint
        uses: reviewdog/action-golangci-lint@master
        with:
          args: run
      - name: Test
        run: make test
      - name: Build
        run: make
